Update to include sample workshop for first class
purduewebdevclub/2017-Beginner-Gitbook pull request #1
Opened 2017-05-30 00:05 UTC by redixhumayun

Let me know what you think. Sorry about the disgusting framework I uploaded on imgur, but did that in a hurry.

2017-05-30 01:00 UTC, maneesht requested changes
Overall, this looks good so far. The example given is somewhat complex because it uses bootstrap classes. This may confuse some students.

2017-05-30 01:00 UTC, maneesht commented on intro-html.md
> +####Tribute Page
Add a space between the hashes and the title

2017-05-30 01:00 UTC, maneesht commented on intro-html.md
> +Beyond these requirements,
Thought needs to be finished.

2017-05-30 19:49 UTC, redixhumayun commented on intro-html.md
> +####Tribute Page
I can try to do the same without Bootstrap. Want me to go ahead and do that? I can host it and send you a link on codepen.io

2017-05-30 19:50 UTC, redixhumayun commented
I can try and create a similar page without bootstrap. Want me to go ahead and do that? I can share on codepen.io later

2017-05-31 04:37 UTC, maneesht commented
Can you do that?

2017-06-04 23:20 UTC, maneesht commented on intro-html.md
> +For the very first workshop, create a simple tribute page to any personality of your choice. The basic requirements for this are that the web page have a navbar at the top, with the name of the perso
Not necessarily a nav bar, just a title section

2017-06-04 23:26 UTC, maneesht commented
Also, don't forget to add very simple boilerplate code for the workshop

2017-06-06 04:10 UTC, maneesht commented
Merged

2017-06-06 04:10 UTC, closed without merging